version: "3.9"
services:
    db:
        image: mysql:8
        volumes:
          - db:/var/lib/mysql
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root123
          MYSQL_DATABASE: db_taller
          MYSQL_USER: user_taller
          MYSQL_PASSWORD: taller123
    dbadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8080:80
        depends_on:
            - db
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root123
            MYSQL_USER: user_taller
            MYSQL_PASSWORD: taller123
    ss1:
        image: rugana90/aos-ss1:0.5
        restart: always
        depends_on:
            - db
        ports:
            - 8081:8080
    ss2:
        image: rugana90/aos-ss2:0.5
        restart: always
        depends_on:
            - db
        ports:
            - 8082:8080
    ss3:
        image: rugana90/aos-ss3:0.5
        restart: always
        depends_on:
            - db
        ports:
            - 8083:8080
    ss4:
        image: rugana90/aos-ss4:0.5
        restart: always
        depends_on:
            - db
        ports:
            - 8084:8080
    ss5: 
        image: rugana90/aos-ss5:0.5
        restart: always
        depends_on:
            - db
        ports:
            - 8085:8080
    ss6: 
        image: rugana90/aos-ss6:0.5
        restart: always
        depends_on:
            - db
        ports:
            - 8086:8080
volumes:
    db: 