#Deployment 1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss1
  labels:
    app: taller
spec:
  selector:
    matchLabels:
      app: taller
  replicas: 1
  template:
    metadata:
      labels:
        app: taller
    spec:
      containers:
        - image: rugana90/aos-ss1:0.5
          name: aos-ss1
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - name: ss1
              containerPort: 8081

---

#Deployment 2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss2
  labels:
    app: taller
spec:
  selector:
    matchLabels:
      app: taller
  replicas: 1
  template:
    metadata:
      labels:
        app: taller
    spec:
      containers:
        - image: rugana90/aos-ss2:0.5
          name: aos-ss2
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - name: ss2
              containerPort: 8082

---

#Deployment 3
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss3
  labels:
    app: taller
spec:
  selector:
    matchLabels:
      app: taller
  replicas: 1
  template:
    metadata:
      labels:
        app: taller
    spec:
      containers:
        - image: rugana90/aos-ss3:0.5
          name: aos-ss3
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - name: ss3
              containerPort: 8083

---              

#Deployment 4
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss4
  labels:
    app: taller
spec:
  selector:
    matchLabels:
      app: taller
  replicas: 1
  template:
    metadata:
      labels:
        app: taller
    spec:
      containers:
        - image: rugana90/aos-ss4:0.5
          name: aos-ss4
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - name: ss4
              containerPort: 8084

---

#Deployment 5
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss5
  labels:
    app: taller
spec:
  selector:
    matchLabels:
      app: taller
  replicas: 1
  template:
    metadata:
      labels:
        app: taller
    spec:
      containers:
        - image: rugana90/aos-ss5:0.5
          name: aos-ss5
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - name: ss5
              containerPort: 8085

---

#Deployment 6
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss6
  labels:
    app: taller
spec:
  selector:
    matchLabels:
      app: taller
  replicas: 1
  template:
    metadata:
      labels:
        app: taller
    spec:
      containers:
        - image: rugana90/aos-ss6:0.5
          name: aos-ss6
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          ports:
            - name: ss6
              containerPort: 8086


---

#Service taller
apiVersion: v1
kind: Service
metadata:
  name: taller
  labels:
    app: taller
spec:
  ports:
    - name: ss1
      port: 8081
      targetPort: 8081
    - name: ss2
      port: 8082
      targetPort: 8082
    - name: ss3
      port: 8083
      targetPort: 8083
    - name: ss4
      port: 8084
      targetPort: 8084
    - name: ss5
      port: 8085
      targetPort: 8085
    - name: ss6
      port: 8086
      targetPort: 8086
  selector:
    app: taller
  type: NodePort