# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.factura_links import FacturaLinks  # noqa: F401,E501
from swagger_server import util


class Factura(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, factura_id: int=None, user_id: int=None, vehiculo_id: int=None, fecha_emision: date=None, importe: float=None, importe_iva: float=None, links: List[FacturaLinks]=None):  # noqa: E501
        """Factura - a model defined in Swagger

        :param factura_id: The factura_id of this Factura.  # noqa: E501
        :type factura_id: int
        :param user_id: The user_id of this Factura.  # noqa: E501
        :type user_id: int
        :param vehiculo_id: The vehiculo_id of this Factura.  # noqa: E501
        :type vehiculo_id: int
        :param fecha_emision: The fecha_emision of this Factura.  # noqa: E501
        :type fecha_emision: date
        :param importe: The importe of this Factura.  # noqa: E501
        :type importe: float
        :param importe_iva: The importe_iva of this Factura.  # noqa: E501
        :type importe_iva: float
        :param links: The links of this Factura.  # noqa: E501
        :type links: List[FacturaLinks]
        """
        self.swagger_types = {
            'factura_id': int,
            'user_id': int,
            'vehiculo_id': int,
            'fecha_emision': date,
            'importe': float,
            'importe_iva': float,
            'links': List[FacturaLinks]
        }

        self.attribute_map = {
            'factura_id': 'facturaId',
            'user_id': 'userId',
            'vehiculo_id': 'vehiculoId',
            'fecha_emision': 'fechaEmision',
            'importe': 'importe',
            'importe_iva': 'importeIVA',
            'links': 'links'
        }
        self._factura_id = factura_id
        self._user_id = user_id
        self._vehiculo_id = vehiculo_id
        self._fecha_emision = fecha_emision
        self._importe = importe
        self._importe_iva = importe_iva
        self._links = links

    @classmethod
    def from_dict(cls, dikt) -> 'Factura':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Factura of this Factura.  # noqa: E501
        :rtype: Factura
        """
        return util.deserialize_model(dikt, cls)

    @property
    def factura_id(self) -> int:
        """Gets the factura_id of this Factura.

        Id Factura  # noqa: E501

        :return: The factura_id of this Factura.
        :rtype: int
        """
        return self._factura_id

    @factura_id.setter
    def factura_id(self, factura_id: int):
        """Sets the factura_id of this Factura.

        Id Factura  # noqa: E501

        :param factura_id: The factura_id of this Factura.
        :type factura_id: int
        """

        self._factura_id = factura_id

    @property
    def user_id(self) -> int:
        """Gets the user_id of this Factura.

        user Id  # noqa: E501

        :return: The user_id of this Factura.
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: int):
        """Sets the user_id of this Factura.

        user Id  # noqa: E501

        :param user_id: The user_id of this Factura.
        :type user_id: int
        """

        self._user_id = user_id

    @property
    def vehiculo_id(self) -> int:
        """Gets the vehiculo_id of this Factura.

        Id vehiculo  # noqa: E501

        :return: The vehiculo_id of this Factura.
        :rtype: int
        """
        return self._vehiculo_id

    @vehiculo_id.setter
    def vehiculo_id(self, vehiculo_id: int):
        """Sets the vehiculo_id of this Factura.

        Id vehiculo  # noqa: E501

        :param vehiculo_id: The vehiculo_id of this Factura.
        :type vehiculo_id: int
        """

        self._vehiculo_id = vehiculo_id

    @property
    def fecha_emision(self) -> date:
        """Gets the fecha_emision of this Factura.

        Fecha de creacion de la factura  # noqa: E501

        :return: The fecha_emision of this Factura.
        :rtype: date
        """
        return self._fecha_emision

    @fecha_emision.setter
    def fecha_emision(self, fecha_emision: date):
        """Sets the fecha_emision of this Factura.

        Fecha de creacion de la factura  # noqa: E501

        :param fecha_emision: The fecha_emision of this Factura.
        :type fecha_emision: date
        """

        self._fecha_emision = fecha_emision

    @property
    def importe(self) -> float:
        """Gets the importe of this Factura.

        Importe total  # noqa: E501

        :return: The importe of this Factura.
        :rtype: float
        """
        return self._importe

    @importe.setter
    def importe(self, importe: float):
        """Sets the importe of this Factura.

        Importe total  # noqa: E501

        :param importe: The importe of this Factura.
        :type importe: float
        """

        self._importe = importe

    @property
    def importe_iva(self) -> float:
        """Gets the importe_iva of this Factura.

        Importe con IVA  # noqa: E501

        :return: The importe_iva of this Factura.
        :rtype: float
        """
        return self._importe_iva

    @importe_iva.setter
    def importe_iva(self, importe_iva: float):
        """Sets the importe_iva of this Factura.

        Importe con IVA  # noqa: E501

        :param importe_iva: The importe_iva of this Factura.
        :type importe_iva: float
        """

        self._importe_iva = importe_iva

    @property
    def links(self) -> List[FacturaLinks]:
        """Gets the links of this Factura.

        Listado de trabajos  # noqa: E501

        :return: The links of this Factura.
        :rtype: List[FacturaLinks]
        """
        return self._links

    @links.setter
    def links(self, links: List[FacturaLinks]):
        """Sets the links of this Factura.

        Listado de trabajos  # noqa: E501

        :param links: The links of this Factura.
        :type links: List[FacturaLinks]
        """

        self._links = links
