# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class HTTPProblem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None, title: str=None, status: float=None, detail: str=None, instance: str=None):  # noqa: E501
        """HTTPProblem - a model defined in Swagger

        :param type: The type of this HTTPProblem.  # noqa: E501
        :type type: str
        :param title: The title of this HTTPProblem.  # noqa: E501
        :type title: str
        :param status: The status of this HTTPProblem.  # noqa: E501
        :type status: float
        :param detail: The detail of this HTTPProblem.  # noqa: E501
        :type detail: str
        :param instance: The instance of this HTTPProblem.  # noqa: E501
        :type instance: str
        """
        self.swagger_types = {
            'type': str,
            'title': str,
            'status': float,
            'detail': str,
            'instance': str
        }

        self.attribute_map = {
            'type': 'type',
            'title': 'title',
            'status': 'status',
            'detail': 'detail',
            'instance': 'instance'
        }
        self._type = type
        self._title = title
        self._status = status
        self._detail = detail
        self._instance = instance

    @classmethod
    def from_dict(cls, dikt) -> 'HTTPProblem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HTTP_Problem of this HTTPProblem.  # noqa: E501
        :rtype: HTTPProblem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this HTTPProblem.

        A URI reference [RFC3986] that identifies the problem type  # noqa: E501

        :return: The type of this HTTPProblem.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this HTTPProblem.

        A URI reference [RFC3986] that identifies the problem type  # noqa: E501

        :param type: The type of this HTTPProblem.
        :type type: str
        """

        self._type = type

    @property
    def title(self) -> str:
        """Gets the title of this HTTPProblem.

        short human-readable summary of the problem type  # noqa: E501

        :return: The title of this HTTPProblem.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this HTTPProblem.

        short human-readable summary of the problem type  # noqa: E501

        :param title: The title of this HTTPProblem.
        :type title: str
        """

        self._title = title

    @property
    def status(self) -> float:
        """Gets the status of this HTTPProblem.

        HTTP status code  # noqa: E501

        :return: The status of this HTTPProblem.
        :rtype: float
        """
        return self._status

    @status.setter
    def status(self, status: float):
        """Sets the status of this HTTPProblem.

        HTTP status code  # noqa: E501

        :param status: The status of this HTTPProblem.
        :type status: float
        """

        self._status = status

    @property
    def detail(self) -> str:
        """Gets the detail of this HTTPProblem.

        human-readable explanation specific to this occurrence of the problem  # noqa: E501

        :return: The detail of this HTTPProblem.
        :rtype: str
        """
        return self._detail

    @detail.setter
    def detail(self, detail: str):
        """Sets the detail of this HTTPProblem.

        human-readable explanation specific to this occurrence of the problem  # noqa: E501

        :param detail: The detail of this HTTPProblem.
        :type detail: str
        """

        self._detail = detail

    @property
    def instance(self) -> str:
        """Gets the instance of this HTTPProblem.

        A URI reference that identifies the specific occurrence of the problem.  It may or may not yield further information if dereferenced  # noqa: E501

        :return: The instance of this HTTPProblem.
        :rtype: str
        """
        return self._instance

    @instance.setter
    def instance(self, instance: str):
        """Sets the instance of this HTTPProblem.

        A URI reference that identifies the specific occurrence of the problem.  It may or may not yield further information if dereferenced  # noqa: E501

        :param instance: The instance of this HTTPProblem.
        :type instance: str
        """

        self._instance = instance
