# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.factura import Factura  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, facturas: List[Factura]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param facturas: The facturas of this InlineResponse200.  # noqa: E501
        :type facturas: List[Factura]
        """
        self.swagger_types = {
            'facturas': List[Factura]
        }

        self.attribute_map = {
            'facturas': 'facturas'
        }
        self._facturas = facturas

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def facturas(self) -> List[Factura]:
        """Gets the facturas of this InlineResponse200.

        array de facturas  # noqa: E501

        :return: The facturas of this InlineResponse200.
        :rtype: List[Factura]
        """
        return self._facturas

    @facturas.setter
    def facturas(self, facturas: List[Factura]):
        """Sets the facturas of this InlineResponse200.

        array de facturas  # noqa: E501

        :param facturas: The facturas of this InlineResponse200.
        :type facturas: List[Factura]
        """

        self._facturas = facturas
